apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermostconfig
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/mattermostconfig"
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mattermostconfig
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermostdata
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/mattermostdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mattermostdata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermostlogs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/mattermostlogs"
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mattermostlogs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermostplugins
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/mattermostplugins"
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mattermostplugins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi

